/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Archivos.AdministradorArchivos;
import Archivos.LectorXML;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import org.xml.sax.SAXException;
import prograpoo1.Vehiculo;

/**
 *
 * @author Javith
 */
public final class DatosVehiculo extends javax.swing.JFrame {
    
    /**
     * Creates new form Interfaz
     */
    public DatosVehiculo(Vehiculo datos) {
        initComponents();
        
        this.labeltTtulo.setText("Vehiculo: ");
       
        
        
    }
    
    private void CargarComponentes(){
        
    
    }
    
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labeltTtulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelAtrib0 = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        subMenuArchivo = new javax.swing.JMenu();
        itemUsuario = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu1 = new javax.swing.JMenu();
        mINuevoChofer = new javax.swing.JMenuItem();
        mINuevoEmpresa = new javax.swing.JMenuItem();
        mINuevoPasajero = new javax.swing.JMenuItem();
        mINuevoVehiculo = new javax.swing.JMenuItem();
        itemSalir = new javax.swing.JMenuItem();
        subMenuEditar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 51));

        labeltTtulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        labelAtrib0.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        subMenuArchivo.setText("Archivo");

        itemUsuario.setText("Usuario");
        subMenuArchivo.add(itemUsuario);
        subMenuArchivo.add(jSeparator1);

        jMenu1.setText("Nuevo");

        mINuevoChofer.setText("Chofer");
        jMenu1.add(mINuevoChofer);

        mINuevoEmpresa.setText("Empresa");
        jMenu1.add(mINuevoEmpresa);

        mINuevoPasajero.setText("Pasajero");
        mINuevoPasajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mINuevoPasajeroActionPerformed(evt);
            }
        });
        jMenu1.add(mINuevoPasajero);

        mINuevoVehiculo.setText("Vehiculo");
        mINuevoVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mINuevoVehiculoActionPerformed(evt);
            }
        });
        jMenu1.add(mINuevoVehiculo);

        subMenuArchivo.add(jMenu1);

        itemSalir.setText("Salir");
        itemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalirActionPerformed(evt);
            }
        });
        subMenuArchivo.add(itemSalir);

        barraMenu.add(subMenuArchivo);

        subMenuEditar.setText("Editar");
        barraMenu.add(subMenuEditar);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labeltTtulo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelAtrib0, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(352, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labeltTtulo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAtrib0, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(376, 376, 376))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
     
    }//GEN-LAST:event_itemSalirActionPerformed

    private void mINuevoPasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mINuevoPasajeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mINuevoPasajeroActionPerformed

    private void mINuevoVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mINuevoVehiculoActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crear().setVisible(true);
            }
        });
    }//GEN-LAST:event_mINuevoVehiculoActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JMenuItem itemUsuario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel labelAtrib0;
    private javax.swing.JLabel labeltTtulo;
    private javax.swing.JMenuItem mINuevoChofer;
    private javax.swing.JMenuItem mINuevoEmpresa;
    private javax.swing.JMenuItem mINuevoPasajero;
    private javax.swing.JMenuItem mINuevoVehiculo;
    private javax.swing.JMenu subMenuArchivo;
    private javax.swing.JMenu subMenuEditar;
    // End of variables declaration//GEN-END:variables
}
