/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Archivos.AdministradorArchivos;
import Archivos.GuardarXML;
import Archivos.LectorXML;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import org.xml.sax.SAXException;
import LogicaNegocios.Pasajero;
import LogicaNegocios.Vehiculo;
import LogicaNegocios.Viaje;

/**
 *
 * @author Javith
 */
public final class MostrarDatos extends javax.swing.JFrame {
    
    /**
     * Creates new form Interfaz
     */
    public MostrarDatos(Vehiculo vehiculo) {
        initComponents();
        CargarComponentes(vehiculo);
    }   
    public MostrarDatos(Pasajero pasajero) {
        initComponents();
       CargarComponentes(pasajero);
    } 
    
    private void CargarComponentes(Vehiculo vehiculo){
        
        this.labeltTtulo.setText("Vehiculo: ");
        this.txtRespuesta0.setText(vehiculo.getPlaca());
        this.txtRespuesta0.setEnabled(false);
        this.labelatrib1.setText("Color: ");
        this.txtRespuesta1.setText(vehiculo.getColor());
        this.txtRespuesta1.setEnabled(false);
        this.labelatrib2.setText("Marca: ");
        this.txtRespuesta2.setText(vehiculo.getMarca());
        this.txtRespuesta2.setEnabled(false);
        this.labelatrib3.setText("Año: ");
        this.txtRespuesta3.setText(String.valueOf(vehiculo.getAgnoFabricacion()));
        this.txtRespuesta3.setEnabled(false);
        this.labelatrib4.setText("Capacidad");
        this.txtRespuesta4.setText(String.valueOf(vehiculo.getCapacidad()));
         this.txtRespuesta4.setEnabled(false);
        this.labelatrib5.setText("kilometraje");
        this.txtRespuesta5.setText(String.valueOf(vehiculo.getKilometraje()));
         this.txtRespuesta5.setEnabled(false);
        this.labelatrib6.setText("VIN");
        this.txtRespuesta6.setText(vehiculo.getVin());
         this.txtRespuesta6.setEnabled(false);
        this.labelatrib7.setText("Sede");
        this.txtRespuesta7.setText(vehiculo.getSede());
         this.txtRespuesta7.setEnabled(false);
        this.labelatrib8.setText("Estado");
        this.comboRespuesta8.removeAllItems();
        this.comboRespuesta8.addItem("Servicio");
        this.comboRespuesta8.addItem("Mantenimiento");
        this.comboRespuesta8.addItem("Fuera Servicio");
        for (int i=0; comboRespuesta8.getMaximumRowCount()>i;i++)
            if (vehiculo.getEstado().equals(comboRespuesta8.getItemAt(i)))
                this.comboRespuesta8.setSelectedIndex(i);
         this.comboRespuesta8.setEnabled(false);
    
    }
    private void CargarComponentes(Pasajero pasajero){
        
        
        this.labeltTtulo.setText("Pasajero: ");
        this.txtRespuesta0.setText(pasajero.getNombre());
        this.txtRespuesta0.setEditable(false);
        this.labelatrib1.setText("Cedula: ");
        this.txtRespuesta1.setText(String.valueOf(pasajero.getCedula()));
        this.txtRespuesta1.setEditable(false);
        this.labelatrib2.setText("Direccion: ");
        this.txtRespuesta2.setText(pasajero.getDireccion().toString());
        this.txtRespuesta2.setEditable(false);
        this.labelatrib3.setText("Correo: ");
        this.txtRespuesta3.setText(pasajero.getCorreo());
        this.txtRespuesta3.setEditable(false);
        this.labelatrib4.setText("Telefono");
        this.txtRespuesta4.setText(String.valueOf(pasajero.getTelefono()));
        this.txtRespuesta4.setEditable(false);
        this.labelatrib5.setVisible(false);
        this.txtRespuesta5.setVisible(false);
        this.labelatrib6.setVisible(false);
        this.txtRespuesta6.setVisible(false);
        this.labelatrib7.setVisible(false);
        this.txtRespuesta7.setVisible(false);
         this.labelatrib8.setVisible(false);
        this.comboRespuesta8.setVisible(false);
        this.btnEditar.setVisible(false);
    }
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDatos = new javax.swing.JPanel();
        labeltTtulo = new javax.swing.JLabel();
        labelatrib1 = new javax.swing.JLabel();
        labeltTtulo1 = new javax.swing.JLabel();
        labelatrib2 = new javax.swing.JLabel();
        labelatrib3 = new javax.swing.JLabel();
        labelatrib4 = new javax.swing.JLabel();
        labelatrib5 = new javax.swing.JLabel();
        labelatrib6 = new javax.swing.JLabel();
        labelatrib7 = new javax.swing.JLabel();
        labelatrib8 = new javax.swing.JLabel();
        txtRespuesta0 = new javax.swing.JTextField();
        txtRespuesta1 = new javax.swing.JTextField();
        txtRespuesta2 = new javax.swing.JTextField();
        txtRespuesta3 = new javax.swing.JTextField();
        txtRespuesta4 = new javax.swing.JTextField();
        txtRespuesta5 = new javax.swing.JTextField();
        txtRespuesta6 = new javax.swing.JTextField();
        txtRespuesta7 = new javax.swing.JTextField();
        comboRespuesta8 = new javax.swing.JComboBox<>();
        btnEditar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        panelDatos.setBackground(new java.awt.Color(255, 255, 255));

        labeltTtulo.setBackground(new java.awt.Color(204, 0, 0));
        labeltTtulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labeltTtulo.setText("1");

        labelatrib1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelatrib1.setText("1");

        labeltTtulo1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        labelatrib2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelatrib2.setText("1");

        labelatrib3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelatrib3.setText("1");

        labelatrib4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelatrib4.setText("1");

        labelatrib5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelatrib5.setText("1");

        labelatrib6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelatrib6.setText("1");

        labelatrib7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelatrib7.setText("1");

        labelatrib8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelatrib8.setText("1");

        txtRespuesta0.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRespuesta0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRespuesta0ActionPerformed(evt);
            }
        });

        txtRespuesta1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRespuesta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRespuesta1ActionPerformed(evt);
            }
        });

        txtRespuesta2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRespuesta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRespuesta2ActionPerformed(evt);
            }
        });

        txtRespuesta3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRespuesta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRespuesta3ActionPerformed(evt);
            }
        });

        txtRespuesta4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRespuesta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRespuesta4ActionPerformed(evt);
            }
        });

        txtRespuesta5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRespuesta5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRespuesta5ActionPerformed(evt);
            }
        });

        txtRespuesta6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRespuesta6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRespuesta6ActionPerformed(evt);
            }
        });

        txtRespuesta7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRespuesta7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRespuesta7ActionPerformed(evt);
            }
        });

        comboRespuesta8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelDatosLayout.createSequentialGroup()
                                .addComponent(labeltTtulo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRespuesta0))
                            .addGroup(panelDatosLayout.createSequentialGroup()
                                .addComponent(labelatrib1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRespuesta1))
                            .addGroup(panelDatosLayout.createSequentialGroup()
                                .addComponent(labelatrib2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRespuesta2))
                            .addGroup(panelDatosLayout.createSequentialGroup()
                                .addComponent(labelatrib3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRespuesta3))
                            .addGroup(panelDatosLayout.createSequentialGroup()
                                .addComponent(labelatrib4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRespuesta4))
                            .addGroup(panelDatosLayout.createSequentialGroup()
                                .addComponent(labelatrib5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRespuesta6))
                            .addGroup(panelDatosLayout.createSequentialGroup()
                                .addComponent(labelatrib6, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRespuesta7))
                            .addGroup(panelDatosLayout.createSequentialGroup()
                                .addComponent(labelatrib7, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRespuesta5))
                            .addGroup(panelDatosLayout.createSequentialGroup()
                                .addComponent(labelatrib8, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboRespuesta8, 0, 335, Short.MAX_VALUE))))
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(btnEditar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDatosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(labeltTtulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(288, Short.MAX_VALUE)))
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labeltTtulo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addComponent(txtRespuesta0)
                        .addGap(3, 3, 3)))
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelatrib1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRespuesta1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelatrib2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRespuesta2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelatrib3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRespuesta3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelatrib4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRespuesta4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelatrib5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRespuesta6, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelatrib6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRespuesta7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelatrib7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRespuesta5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelatrib8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboRespuesta8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnEditar)
                .addContainerGap())
            .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDatosLayout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addComponent(labeltTtulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(313, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnAceptar)
                        .addGap(69, 69, 69)
                        .addComponent(btnCancelar)))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRespuesta0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRespuesta0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRespuesta0ActionPerformed

    private void txtRespuesta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRespuesta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRespuesta1ActionPerformed

    private void txtRespuesta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRespuesta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRespuesta2ActionPerformed

    private void txtRespuesta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRespuesta3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRespuesta3ActionPerformed

    private void txtRespuesta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRespuesta4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRespuesta4ActionPerformed

    private void txtRespuesta5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRespuesta5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRespuesta5ActionPerformed

    private void txtRespuesta6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRespuesta6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRespuesta6ActionPerformed

    private void txtRespuesta7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRespuesta7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRespuesta7ActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
    this.txtRespuesta0.setEnabled(true);
    this.txtRespuesta1.setEnabled(true);
    this.txtRespuesta2.setEnabled(true);
    this.txtRespuesta3.setEnabled(true);
    this.txtRespuesta4.setEnabled(true);
    this.txtRespuesta5.setEnabled(true);
    this.txtRespuesta6.setEnabled(true);
    this.txtRespuesta7.setEnabled(true);
    this.comboRespuesta8.setEnabled(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        try {
            if(this.btnEditar.isEnabled()){
            Vehiculo nuevo = new Vehiculo(this.txtRespuesta0.getText(), this.txtRespuesta1.getText(), this.txtRespuesta2.getText(),Integer.parseInt((this.txtRespuesta3.getText())), Integer.parseInt(this.txtRespuesta4.getText()), Double.valueOf(this.txtRespuesta5.getText()), this.txtRespuesta6.getText(), this.txtRespuesta7.getText(), this.comboRespuesta8.getItemAt(comboRespuesta8.getSelectedIndex()));
            GuardarXML garda =new GuardarXML(nuevo);
        }  
        } catch (Exception e) {
        }
        
        this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JComboBox<String> comboRespuesta8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelatrib1;
    private javax.swing.JLabel labelatrib2;
    private javax.swing.JLabel labelatrib3;
    private javax.swing.JLabel labelatrib4;
    private javax.swing.JLabel labelatrib5;
    private javax.swing.JLabel labelatrib6;
    private javax.swing.JLabel labelatrib7;
    private javax.swing.JLabel labelatrib8;
    private javax.swing.JLabel labeltTtulo;
    private javax.swing.JLabel labeltTtulo1;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JTextField txtRespuesta0;
    private javax.swing.JTextField txtRespuesta1;
    private javax.swing.JTextField txtRespuesta2;
    private javax.swing.JTextField txtRespuesta3;
    private javax.swing.JTextField txtRespuesta4;
    private javax.swing.JTextField txtRespuesta5;
    private javax.swing.JTextField txtRespuesta6;
    private javax.swing.JTextField txtRespuesta7;
    // End of variables declaration//GEN-END:variables
}
